name: flug_tag
description: A dart-tags lib sample.

dependencies:
  flutter:
    sdk: flutter

  dart_tags:
    git:
      url: git://github.com/NiKoTron/dart-tags.git

  path_provider: ^1.1.0
  permission_handler: ^3.1.0
  #  file_picker: ^1.3.7
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - data/mp3.mp3
