name: flug_tag
description: A dart-tags lib sample.

dependencies:
  flutter:
    sdk: flutter

  simple_permissions: ^0.1.4

  path_provider: ^0.4.0

  dart_tags: ^0.0.7

  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - data/mp3.mp3
