name: flug_tag
description: A dart-tags lib sample.

dependencies:
  flutter:
    sdk: flutter

  dart_tags:
    git:
      url: git://github.com/NiKoTron/dart-tags.git

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - data/mp3.mp3
